# Generated by Django 6.0.1 on 2026-01-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_number',
            new_name='invoice_number',
        ),
    ]
