# Generated by Django 5.2.8 on 2025-11-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_pricepernight_room_price_per_night_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hôtel associé pour les administrateurs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel'),
        ),
    ]
