# Generated by Django 5.2.8 on 2025-11-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pricePerNight',
            new_name='price_per_night',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='roomNumber',
            new_name='room_number',
        ),
    ]
