# Generated by Django 6.0.1 on 2026-01-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_is_active_hotel_location_alter_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
