# Generated by Django 6.0.1 on 2026-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_phone_hotel_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
