# Generated by Django 6.0.1 on 2026-01-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_room_amenities_room_capacity_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
