# Generated by Django 6.0.1 on 2026-01-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite'), ('VIP', 'VIP'), ('SIMPLE', 'Simple'), ('TWIN', 'Twin'), ('TRIPLE', 'Triple'), ('FAMILY', 'Family'), ('PRESIDENTIAL', 'Presidential')], default='SINGLE', max_length=20),
        ),
    ]
