# Generated by Django 6.0.1 on 2026-02-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel_name',
        ),
    ]
